baseURL: "https://nicce.dev/"
title: Curiosity dooms us
copyright: © 2022 Niklas Saari
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
      - html
      - rss
      - json # is necessary

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio ]
  author: Niklas Saari
  # author: ["Me", "You"] # multiple authors
  # images: ["/images/binary.svg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true 
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/images/binary.svg"
    apple_touch_icon: "/images/binary.svg"
    safari_pinned_tab: "/images/binary.svg"

  label:
    text: "Home"
    icon: /images/binary.svg
    iconHeight: 25

  # profile-mode
  profileMode:
    enabled: True # needs to be explicitly set
    title: Spiralling curiosity 
    subtitle: "Welcome to my blog. Blog about computer engineering and hacking in traditional sense. There isn't much more here to see than my personal documentation and learning process."
    imageUrl: "/images/binary.svg"
    # imageWidth: 45 both variables disabled from theme
    # imageHeight: 45 disabled from theme
    imageTitle: According to some, spiral is a symbolic route into higher level of consciousness. Not Debian logo.
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: About 
        url: about

  # home-info mode
  homeInfoParams:
    Title: ""
    Content: Welcome to my blog. There isn't much more here to see.

      # socialIcons:
      # - name: github
      # url: "https://github.com/Nicceboy"


  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/Nicceboy/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html


  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Categories
      url: /tags/
      weight: 20
    - identifier: search 
      name: Search
      url: /search/ 
      weight: 30
    - identifier: about
      name: About
      url: /about/ 
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

